# Generated by Django 3.1.1 on 2020-09-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='course/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
