# Generated by Django 3.1.1 on 2020-09-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cws', '0002_auto_20200930_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_slug',
            new_name='slug',
        ),
    ]
