# Generated by Django 3.1.1 on 2020-10-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cws', '0003_auto_20200930_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='item',
        ),
    ]
